# Composible action to setup the datman + dependencies

name: Build Datman
description: Build the container env for datman workflows
runs:
  using: composite
  steps:
    - name: Install python
      run: sudo apt update && sudo apt install -y git python3 python3-pip python3-venv
      shell: bash
    - name: Update pip
      run: python -m pip install --upgrade pip
      shell: bash
    - name: Install datman + base requirements
      run: python -m pip install .
      shell: bash
