version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie-node-browsers
    steps:
      - checkout
      - run:
          name: Install nose
          command: |
            pip install --user nose==1.3.4
            pwd
            mkdir outputs
            ls -r / > outputs/out.txt
      - store_artifacts:
          path: outputs/
          destinations: tr1
