version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie-node-browsers
    steps:
      - checkout
      - run:
          name: Install nose
          command: |
            pip install --user nose==1.3.4
            echo 'export PATH=/home/circleci/.local/bin/:$PATH' >> $BASH_ENV
      -run:
          name: Test outputs
          command: |
            pwd
            mkdir outputs
            ls -R / > outputs/ls_R.txt
            pip list > outputs/pip_list.txt
      - store_artifacts:
          path: outputs/
          destinations: tr1
      - run:
          name: Try to run nose
          command: |
            cd datman
            nosetests
