version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie-node-browsers
    steps:
      - checkout
      - run:
          name: Install nose
          command: |
            pip install -r nose=1.3.4
            nosetests
