version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8-buster
    steps:
      - checkout
      - run:
          name: Install package using setup.py
          command: |
            pip install .
      - run:
          name: Run pytests
          command: |
            mkdir test_results
            pytest --junit-xml test_results/pytest_report.xml tests/
      - store_test_results:
          path: test_results/
