version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie-node-browsers
        environment:
          DATMAN: /home/circleci/project/datman
    steps:
      - checkout
      - run:
          name: Install nose
          command: |
            pip install --user nose==1.3.4
            echo 'export PATH=/home/circleci/.local/bin/:$PATH' >> $BASH_ENV
            pwd
            mkdir outputs
            sudo pip list > outputs/pip_list.txt
      - store_artifacts:
          path: outputs/
          destinations: tr1
      - run:
          name: Try to run nose
          command: |
            cd datman
            echo 'export PATH=${DATMAN}/bin/:${DATMAN}/assets/:$PATH:${DATMAN}/:${DATMAN}/datman/'
            echo 'export MATLABPATH=${DATMAN}/assets/:$MATLABPATH'
            echo 'export PYTHONPATH=${DATMAN}/assets/:${DATMAN}/:$PYTHONPATH'
            echo 'export DATMAN_ASSETS=${DATMAN}/assets/'
            printenv > outputs/printenv.txt
            nosetests
