version: 2
jobs:
  build:
    working_directory: ~/datman
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - restore_cache:
          key: tox-env-{{ checksum "setup.cfg" }}
      - run:
          command: |
            tox
      - save_cache:
          key: tox-env-{{ checksum "setup.cfg" }}
          paths: .tox
    store-test-results:
      path: tests/results/
