version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie-node-browsers
        environment:
          DATMAN: /home/circleci/project/datman
    steps:
      - checkout
      - run:
          name: Clone config
          command: |
            git clone git@github.com:Mathu-M/datman-config.git
            echo 'export DM_CONFIG=/home/circleci/datman-config/tigrlab_config.yaml'
      - run:
          name: Install requirements
          command: |
            pip install --user -r requirements.txt
            echo 'export PATH=/home/circleci/.local/bin/:$PATH' >> $BASH_ENV
            pwd
            ls -R
            mkdir outputs
            sudo pip list > outputs/pip_list.txt
      - store_artifacts:
          path: outputs/
          destinations: tr1
      - run:
          name: Try to run nose
          command: |
            ls
            echo 'export PATH=${DATMAN}/bin/:${DATMAN}/assets/:$PATH:${DATMAN}/:${DATMAN}/datman/'
            echo 'export MATLABPATH=${DATMAN}/assets/:$MATLABPATH'
            echo 'export PYTHONPATH=${DATMAN}/assets/:${DATMAN}/:$PYTHONPATH'
            echo 'export DATMAN_ASSETS=${DATMAN}/assets/'
            nosetests
            printenv
