version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie-node-browsers
        environment:
          DATMAN: /home/circleci/datman
    steps:
      - checkout:
          path: /home/circleci/datman
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "/home/circleci/datman/requirements.txt" }}
      - run:
          name: Install requirements in venv
          command: |
            python -m virtualenv venv
            source venv/bin/activate
            pip install -r /home/circleci/datman/requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "/home/circleci/datman/requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Test outputs
          command: |
            pwd
            ls -hlR /home/circleci/
            mkdir outputs
            sudo pip list > outputs/pip_list.txt
      - run:
          name: Try to run nose
          command: |
            ls
            echo 'export PATH=${DATMAN}/bin/:${DATMAN}/assets/:$PATH:${DATMAN}/:${DATMAN}/datman/' >> $BASH_ENV
            echo 'export MATLABPATH=${DATMAN}/assets/:$MATLABPATH' >> $BASH_ENV
            echo 'export PYTHONPATH=${DATMAN}/assets/:${DATMAN}/:$PYTHONPATH' >> $BASH_ENV
            echo 'export DATMAN_ASSETS=${DATMAN}/assets/'
            printenv > outputs/printenv.txt
            source venv/bin/activate
            cd /home/circleci/datman
            nosetests > /home/circleci/project/outputs/nosetests.txt
      - store_artifacts:
          path: /home/circleci/project/outputs
          destination: out
      - store_test_results:
          path: /home/circleci/project/outputs
