### configuration of all run.sh scripts in TIGR lab server
---
PipelineSettings:
  - 'dm-sftp-sync.sh' :
      message: Get new scans
      arguments:
        - '${MRUSER}@mrftp.camhpet.ca'
        - '"${MRFOLDER}"'
        - '${PROJECTDIR}/data/zips'

  - 'link.py' :
      message: Link scans
      arguments:
       - '--lookup=${PROJECTDIR}/metadata/scans.csv'
       - '${PROJECTDIR}/data/dicom/'
       - '${PROJECTDIR}/data/zips/*.zip'

  - 'dm-xnat-upload.sh' :
      message: Uploading new scans to XNAT
      arguments:
        - '${XNAT_PROJECT}'
        - '${XNAT_ARCHIVE_CMH}'
        - '${PROJECTDIR}/data/dicom'
        - '${PROJECTDIR}/metadata/xnat-credentials'

  - 'xnat-extract.py' :
      message: Extract new scans from XNAT
      IterateOverSites : Yes
      arguments:
        - '--blacklist ${PROJECTDIR}/metadata/blacklist.csv'
        - '--datadir ${PROJECTDIR}/data'
        - '--exportinfo ${PROJECTDIR}/metadata/exportinfo.csv'
        - '${XNAT_ARCHIVE_<site>}/*'
      modules: slicer/4.4.0 mricron/0.20140804 minc-toolkit/1.0.01

  - 'dm-check-headers.py' :
      message: Checking DICOM headers
      IterateOverSites : Yes
      arguments:
        - '--filter <site>'
        - '${<site>_STANDARD}'
        - '${PROJECTDIR}/qc/logs'
        - "${PROJECTDIR}/data/dcm/"

  - 'dm-check-bvecs.py' :
      message: Checking gradient directions
      IterateOverSites : Yes
      arguments:
        - '--filter <site>'
        - '${<site>_STANDARD}'
        - '${PROJECTDIR}/qc/logs'
        - "${PROJECTDIR}/data/nii/"

  - 'dm-link-sprl.sh' :
      message: 'Linking Spiral Scans'
      runif : '"SPRL" in ScanTypes'
      arguments: ['${PROJECTDIR}/data']

  - 'dm-proc-split-pdt2.py' :
      message: 'Split the PDT2 images'
      runif: '"PDT2" in ScanTypes'
      runInsideSubShell : Yes
      arguments: ['${PROJECTDIR}/data/nii/*/*_PDT2_*.nii.gz']
      modules: FSL/5.0.7

  - 'qc.py' :
      message: Generating QC documents
      arguments:
        - '--datadir ${PROJECTDIR}/data/'
        - '--qcdir ${PROJECTDIR}/qc'
        - '--dbdir ${PROJECTDIR}/qc'
      modules: AFNI/2014.12.16 FSL/5.0.7 matlab/R2013b_concurrent

  - 'qc-report.py' :
      arguments: ['${PROJECTDIR}']

  - 'qc-phantom.py' :
      message: Updating phantom plots
      runif: 'len(SiteNames) > 1'
      modules: AFNI/2014.12.16 FSL/5.0.7 matlab/R2013b_concurrent
      arguments:
        - ${PROJECTDIR}
        - '40'
        - '/archive/data-2.0/code/datman/assets/'
        - '${SITES}'
        - '--adni'
        - '--fmri'

  - 'web-build.py':
      runif: 'len(SiteNames) > 1'
      arguments: ['${PROJECTDIR}']

  - 'dm-proc-dtifit.py' :
      message: 'Running dtifit'
      runif: 'len([s for s in ScanTypes if "DTI" in s]) > 1'
      arguments:
        - '--inputdir ${PROJECTDIR}/data/nii'
        - '--outputdir ${PROJECTDIR}/data/dtifit'
      modules: FSL/5.0.7

  - 'dtifit-qc.py' :
      message: 'Running ditfit qc'
      runif: '"DTI60-1000" in ScanTypes'
      arguments:
        - '--tag DTI60'
        - '${PROJECTDIR}/data/dtifit/'
      modules: FSL/5.0.7

  - 'dm-proc-enigmadti.py' :
      message: 'Running enignmaDTI'
      runif: "'DTI60-1000' in ScanTypes"
      arguments:
        - '--calc-all'
        - '--tag2 DTI60'
        - '--QC-transfer ${PROJECTDIR}/metadata/checklist.csv'
        - '${PROJECTDIR}/data/dtifit'
        - '${PROJECTDIR}/data/enigmaDTI'
      modules: FSL/5.0.7

  - 'dm-proc-freesurfer.py' :
      message: 'Running freesurfer'
      runif: "'T1' in ScanTypes"
      arguments:
       - '--QC-transfer ${PROJECTDIR}/metadata/checklist.csv '
       - '${PROJECTDIR}/data/nii/'
       - '${PROJECTDIR}/data/freesurfer/'
      modules: freesurfer/5.3.0
      enviroment: 'export SUBJECTS_DIR=${PROJECTDIR}/data/freesurfer'

  - 'dm-proc-ea.py' :
      message: 'Analyzing empathic accuracy data'
      runif: "'EMP' in ScanTypes"
      arguments:
        - '${PROJECTDIR}'
        - '/scratch/clevis'
        - '/archive/data-2.0/code/datman/assets/150409-compcor-nonlin-8fwhm.sh'
        - '${PROJECTDIR}/metadata/design'
      modules: freesurfer/5.3.0 AFNI/2014.12.16 FSL/5.0.7 matlab/R2013b_concurrent
      enviroment: 'export SUBJECTS_DIR=${PROJECTDIR}/data/freesurfer'

  - 'dm-proc-imob.py' :
      message: 'Analyzing imitate observe data'
      runif: "('IMI' in ScanTypes) & ('OBS' in ScanTypes)"
      arguments:
       - '${PROJECTDIR}'
       - '/scratch/clevis'
       - '/archive/data-2.0/code/datman/assets/150409-compcor-nonlin-8fwhm.sh'
       - '${PROJECTDIR}/metadata/design'
      modules: freesurfer/5.3.0 AFNI/2014.12.16 FSL/5.0.7 matlab/R2013b_concurrent
      enviroment: 'export SUBJECTS_DIR=${PROJECTDIR}/data/freesurfer'

  - 'dm-proc-rest.py' :
      message: 'Analyzing resting state data'
      runif: "'RST' in ScanTypes"
      arguments:
        - '${PROJECTDIR}'
        - '/scratch/clevis'
        - '/archive/data-2.0/code/datman/assets/151012-tedmethod-compcor-lowpass-nonlin-10fwhm.sh'
        - '/archive/data-2.0/code/datman/assets/shen_1mm_268_parcellation.nii.gz'
        - 'RST'
        - 'SPRL'
      modules: freesurfer/5.3.0 AFNI/2014.12.16 FSL/5.0.7 matlab/R2013b_concurrent
      enviroment: 'export SUBJECTS_DIR=${PROJECTDIR}/data/freesurfer'

ExportSettings:
  T1:         {'nii', 'dcm', 'mnc'}
  PDT2:       {'nii', 'dcm'}
  T2:         {'nii', 'dcm'}
  PD:         {'nii', 'dcm'}
  FLAIR:      {'nii', 'dcm'}
  RST:        {'nii', 'dcm'}
  SPRL:       {'nii'}
  VN-SPRL:    {'nii'}
  OBS:        {'nii', 'dcm'}
  IMI:        {'nii', 'dcm'}
  EMP:        {'nii', 'dcm'}
  NBK:        {'nii', 'dcm'}
  DTI60-1000: {'nii', 'dcm', 'nrrd'}
  DTI60-29-1000: {'nii', 'dcm', 'nrrd'}
  DTI60-20-1000: {'nii', 'dcm', 'nrrd'}
  DTI33-4500: {'nii', 'dcm', 'nrrd'}
  DTI33-3000: {'nii', 'dcm', 'nrrd'}
  DTI33-1000: {'nii', 'dcm', 'nrrd'}
  FMAP-6.5:   {'nii', 'dcm'}
  FMAP-8.5:   {'nii', 'dcm'}
  FMAP:       {'nii', 'dcm'}
  MRS-DLPFC:  {'nii', 'dcm'}
  MRS-sgACC:  {'nii', 'dcm'}

Projects:
  ANDT:     '/archive/data-2.0/ANDT'
  ASDD:     '/archive/data-2.0/ASDD'
  COGBDO:   '/archive/data-2.0/COGBDO'
  COGBDY:   '/archive/data-2.0/COGBDY'
  DTI_CMH:  '/archive/data-2.0/DTI/CMH'
  PACTMD:   '/archive/data-2.0/PACTMD'
  PRELAPSE: '/archive/data-2.0/PRELAPSE'
  RTMSWM:   '/archive/data-2.0/RTMSWM'
  STOPPD:   '/archive/data-2.0/STOPPD'
  SPINS:    '/archive/data-2.0/SPINS'
  VIPR:     '/archive/data-2.0/VIPR'
