name: Assign PR Reviewers

on:
  pull_request_target:
    branches: [main]
    types: [opened]

jobs:
  assign-reviewers:
    runs-on: ubuntu-20.04
    steps:
      - name: Auto Assign Action
        uses: kentaro-m/auto-assign-action@v1.2.3
