name: Prepare test results

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/setup_datman
        with:
          py-version: '3.8'

      - name: Install testing requirements
        run: pip install .[test]

      - name: Make coverage report
        run: |
          pytest --junitxml=/tmp/pytest.xml \
                 --cov-report=term-missing \
                 --cov=bin \
                 --cov=datman \
                 tests/ | tee /tmp/pytest-coverage.txt

      - uses: actions/upload-artifact@v3
        with:
          name: pytest
          path: |
            /tmp/pytest.xml
            /tmp/pytest-coverage.txt

  test-alt-py-versions:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/setup_datman
        with:
          py-version: ${{ matrix.python }}

      - name: Install testing requirements
        run: pip install .[test]

      - name: Run tests
        run: pytest -v ./tests
