# Don't change this name or it'll change the text of the badge for the workflow :)
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/setup_datman
        with:
          py-version: '3.8'

      - name: Install testing requirements
        run: pip install .[test]

      - name: Make coverage report
        run: |
          pytest --junitxml=/tmp/pytest.xml \
                 --cov-report=term-missing \
                 --cov=bin \
                 --cov=datman \
                 tests/ | tee /tmp/pytest-coverage.txt

      - name: Add coverage comment
        id: coverage
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: /tmp/pytest-coverage.txt
          junitxml-path: /tmp/pytest.xml
          report-only-changed-files: true
          github-token: ${{ secrets.DATMAN_COVERAGE_COMMENT }}

      - name: Create/update coverage badge
        if: github.event_name == 'push'
        uses: schneegans/dynamic-badges-action@v1.4.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: cffe8a0a522de7697edacbf74f70a7e1
          filename: datman-coverage.json
          label: Coverage
          message: ${{ steps.coverage.outputs.coverage }}
          valColorRange: ${{ steps.coverage.outputs.coverage }}
          maxColorRange: 100
          minColorRange: 0

      - name: Fail the check if a test has failed
        if: ${{ steps.coverage.outputs.failures != 0 }}
        run: exit 1

  test-alt-py-versions:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/setup_datman
        with:
          py-version: ${{ matrix.python }}

      - name: Install testing requirements
        run: pip install .[test]

      - name: Run tests
        run: pytest -v ./tests
